"""sequence

Revision ID: 85feed5b11ce
Revises: 
Create Date: 2020-01-28 09:59:14.915251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85feed5b11ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(256), nullable=False),
    sa.Column('sequence', sa.String(10000), nullable=False),
    sa.Column('description', sa.String(10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence')
    # ### end Alembic commands ###
